{
 "title": "Selectable Setts Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Sett",
    "label": "Sett",
    "query": {
     "query": "sett{param=\"pricePerShare\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Price Per Share",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sett{param=\"pricePerShare\", sett=~\"$Sett\"}",
     "legendFormat": "{{sett}}"
    }
   ]
  },
  {
   "title": "Total Supply",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sett{param=\"totalSupply\", sett=~\"$Sett\"}",
     "legendFormat": "{{sett}}"
    }
   ]
  },
  {
   "title": "Available",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sett{param=\"available\", sett=~\"$Sett\"}",
     "legendFormat": "{{sett}}"
    }
   ]
  },
  {
   "title": "Balance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sett{param=\"balance\", sett=~\"$Sett\"}",
     "legendFormat": "{{sett}}"
    }
   ]
  }
 ]
}