{
 "title": "Treasury",
 "description": "A overview across all of our wallets and what the DAO holds",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Totals - USD Normalized",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "(sum(wallets{param=\"usdBalance\", token!~\".*DIGG\", token!~\".*BADGER\", walletName!~\"uniswap_rewards\"})) + sum(bsc_wallets{param=\"usdBalance\"})",
     "legendFormat": "Grand Total"
    },
    {
     "expr": "sort_desc(sum by(token) (wallets{param=\"usdBalance\", token!~\".*DIGG\", token!~\".*BADGER\", walletName!~\"uniswap_rewards\"}) != 0)",
     "legendFormat": "{{token}}"
    },
    {
     "expr": "sort_desc(sum by(token) (bsc_wallets{param=\"usdBalance\"}) != 0)",
     "legendFormat": "BSC - {{token}}"
    }
   ]
  },
  {
   "title": "Single Asset Bitcoin",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "targets": [
    {
     "expr": "sum by (token) (wallets{token=~\".*BTC.*\", chain=\"ETH\", param=\"balance\"} )",
     "legendFormat": "{{token}}"
    }
   ]
  },
  {
   "title": "Single Asset Bitcoin - USD",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by (token) (wallets{token=~\".*BTC.*\", param=\"usdBalance\"} != 0)",
     "legendFormat": "{{token}} - USD value"
    }
   ]
  },
  {
   "title": "WBTC/ETH LP tokens (Underlying)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "currencyBTC" }
   ],
   "targets": [
    {
     "expr": "(sum(wallets{token=\"slpWbtcEth\",param=\"balance\"}) / sum(lptokens{token=\"slpWbtcEth\",param=\"totalLpTokenSupply\"})) * sum(lptokens{token=\"slpWbtcEth\", param=\"WETH_supply\"})"
    },
    {
     "expr": "(sum(wallets{token=\"slpWbtcEth\", param=\"balance\"}) / sum(lptokens{token=\"slpWbtcEth\",param=\"totalLpTokenSupply\"})) * sum(lptokens{token=\"slpWbtcEth\", param=\"WBTC_supply\"})"
    }
   ]
  },
  {
   "title": "WBTC/ETH LP  (USD) + LP Token Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "USD Value" }
   ],
   "targets": [
    {
     "expr": "sum(wallets{token=\"slpWbtcEth\", param=\"usdBalance\"})",
     "legendFormat": "USD"
    },
    {
     "expr": "sum(wallets{token=\"slpWbtcEth\", param=\"balance\"})",
     "legendFormat": "LP Tokens"
    }
   ]
  },
  {
   "title": "CVX Tokens",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (token) (wallets{token=~\".*CVX.*\", param=\"balance\", walletName!~\"badgertree\"}) != 0   ",
     "legendFormat": "{{token}} "
    }
   ]
  },
  {
   "title": "CVX Tokens",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (token) (wallets{token=~\".*CRV.*\", param=\"balance\", walletName!~\"badgertree\"}) != 0   ",
     "legendFormat": "{{token}} "
    }
   ]
  },
  {
   "title": "ARB - USD",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by(token) (wallets{param=\"usdBalance\", chain=\"ARB\"}) != 0",
     "legendFormat": "{{token}}"
    }
   ]
  },
  {
   "title": "Badgretree - Rewards to be claimed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "wallets{walletName=\"badgertree\", param=\"usdBalance\"} != 0  ",
     "legendFormat": "{{token}}"
    }
   ]
  }
 ]
}