{
 "title": "Sett Deposits/AUM Overview - BSC",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Total AUM - USD",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "yaxes": [
    { "format": "currencyUSD", "label": "Per Group" }
   ],
   "targets": [
    {
     "expr": "bsc_sett{token=\"cakeBnbBtcb\", param=\"balance\"}  * on(token) bsc_lp{token=\"cakeBnbBtcb\", param=\"usdPricePerShare\"}",
     "legendFormat": "BTC/BNB"
    },
    {
     "expr": "sum(bsc_sett{token=\"cakebBadgerBtcb\", param=\"balance\"} * on(token) bsc_lp{token=\"cakebBadgerBtcb\", param=\"usdPricePerShare\"})",
     "legendFormat": "BBADGER LP"
    },
    {
     "expr": "sum(bsc_sett{token=\"cakebDiggBtcb\", param=\"balance\"} * on(token) bsc_lp{token=\"cakebDiggBtcb\", param=\"usdPricePerShare\"})",
     "legendFormat": "DIGG LP"
    },
    { "expression": "$B+$D+$E", "type": "math" }
   ]
  },
  {
   "title": "bDIGG LP deposits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "yaxes": [
    { "format": "currencyBTC", "label": "bDIGG" }
   ],
   "targets": [
    {
     "expr": "(bsc_sett{token=\"cakebDiggBtcb\", param=\"balance\"} /  on (token) (bsc_lp{token=\"cakebDiggBtcb\",param=\"totalLpTokenSupply\"})) *  on (token) (bsc_lp{token=\"cakebDiggBtcb\", param=\"bDIGG_supply\"})  ",
     "legendFormat": "{{token}} - DIGG"
    },
    {
     "expr": "(bsc_sett{token=\"cakebDiggBtcb\", param=\"balance\"} /  on (token) (bsc_lp{token=\"cakebDiggBtcb\",param=\"totalLpTokenSupply\"})) *  on (token) (bsc_lp{token=\"cakebDiggBtcb\", param=\"BTCB_supply\"})    ",
     "legendFormat": "{{token}} - BTCb"
    }
   ]
  },
  {
   "title": "bBADGER LP deposits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "bBADGER" }
   ],
   "targets": [
    {
     "expr": "(bsc_sett{token=\"cakebBadgerBtcb\", param=\"balance\"} /  on (token) (bsc_lp{token=\"cakebBadgerBtcb\",param=\"totalLpTokenSupply\"})) *  on (token) (bsc_lp{token=\"cakebBadgerBtcb\", param=\"bBADGER_supply\"})  ",
     "legendFormat": "{{token}} - DIGG"
    },
    {
     "expr": "(bsc_sett{token=\"cakebBadgerBtcb\", param=\"balance\"} /  on (token) (bsc_lp{token=\"cakebBadgerBtcb\",param=\"totalLpTokenSupply\"})) *  on (token) (bsc_lp{token=\"cakebBadgerBtcb\", param=\"BTCB_supply\"})  ",
     "legendFormat": "{{token}} - BTCb"
    }
   ]
  },
  {
   "title": "BTCb/BNB Cake LP deposits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "BNB" }
   ],
   "targets": [
    {
     "expr": "(bsc_sett{token=\"cakeBnbBtcb\",param=\"balance\"}  / on(token)   bsc_lp{token=\"cakeBnbBtcb\",param=\"totalLpTokenSupply\"}) * on(token) bsc_lp{token=\"cakeBnbBtcb\", param=~\"WBNB_supply\"}",
     "legendFormat": "BNB"
    },
    {
     "expr": "(bsc_sett{token=\"cakeBnbBtcb\",param=\"balance\"}  / on(token)   bsc_lp{token=\"cakeBnbBtcb\",param=\"totalLpTokenSupply\"}) * on(token) bsc_lp{token=\"cakeBnbBtcb\", param=~\"BTCB_supply\"}",
     "legendFormat": "BTCb"
    }
   ]
  },
  {
   "title": "cake BTC/BNB LP Tokens",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bsc_sett{token=\"cakeBnbBtcb\",param=\"balance\"} ",
     "legendFormat": "BTCb/BNB Cake LP tokens"
    }
   ]
  }
 ]
}