{
 "title": "Homepage",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Intro",
   "type": "text",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 0 },
   "options": {
    "content": "## Badger DAOWatch - Community Metrics\n\nThese metrics are collected real time from the blockchain and stored in a database.  As a result the data here is very very very current, but may have historical glitches when there were collection problems.  These dashboards are intended to understand the basic state of things and should not be taken as absolute truth.  All USD prices are based on the Coingecko API.\n\n#### What you can do\n\n- Click on the info link (top left) of any panel to go to a more detailed dashboards\n- Select the timerange you would like to view using the time picker on the top left\n- Use the search icon to explore/search for all other available dashboards.\n\n#### How you can contribute\nThis is an opensource project.  Grafana is easy to use.  We are happy to give editor access to anyone who would like to experiment with creating dashboards.  Also welcome contributions on the collector.\n\nContact Tritium - VLK in Badger Discord for editor UI access.\n\nAll sourcode to bring this online can be found at https://github.com/DevOps4DeFi/scout. Forks and pull requests are welcomed.\n"
   }
  },
  {
   "title": "Coingecko - Spot Price",
   "type": "stat",
   "gridPos": { "h": 2, "w": 19, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (token) (coingecko_prices{token=~\".*BADGER\",countercurrency=\"usd\"})",
     "legendFormat": "{{token}}"
    },
    {
     "expr": "sum by (token) (coingecko_prices{token=\"WBTC\", countercurrency=\"usd\"})",
     "legendFormat": "BTC"
    },
    {
     "expr": "sum by (token) (coingecko_prices{token=~\".*DIGG\",countercurrency=\"usd\"})",
     "legendFormat": "{{token}}"
    }
   ]
  },
  {
   "title": "Badger Setts ROI ETH",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (sett) (settRoi{targetChain=\"eth\", source=\"none\", param=\"ROI\"})",
     "legendFormat": "{{sett}}"
    }
   ]
  },
  {
   "title": "Badger Setts ROI Arbitrum",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (sett) (settRoi{targetChain=\"arbitrum\", source=\"none\", param=\"ROI\"})",
     "legendFormat": "{{sett}}"
    }
   ]
  },
  {
   "title": "Badger Setts ROI Polygon",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (sett) (settRoi{targetChain=\"matic\", source=\"none\", param=\"ROI\"})",
     "legendFormat": "{{sett}}"
    }
   ]
  },
  {
   "title": "Sett ROI Over Time ETH",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (sett) (settRoi{targetChain=\"eth\", source=\"none\", param=\"ROI\"})",
     "legendFormat": "{{sett}}"
    }
   ]
  },
  {
   "title": "Sett ROI Over Time Polygon",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (sett) (settRoi{targetChain=\"matic\", source=\"none\", param=\"ROI\"})",
     "legendFormat": "{{sett}}"
    }
   ]
  },
  {
   "title": "Sett ROI Over Time Arbitrum",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (sett) (settRoi{targetChain=\"arbitrum\", source=\"none\", param=\"ROI\"})",
     "legendFormat": "{{sett}}"
    }
   ]
  },
  {
   "title": "Bitcoin value of BTC native Setts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (sett) (sett{token=~\".*BTC\", param=\"balance\"} )",
     "legendFormat": "{{sett}}"
    },
    {
     "expr": "sett{sett=\"byvWBTC\", param=\"balance\"}",
     "legendFormat": "{{sett}}"
    }
   ]
  },
  {
   "title": "Time since last cycle",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-(badgertree{chain=~\"..*\"})",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Most recent block processed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 9, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blocks{chain=~\"..*\"}",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Ethereum - Total AUM - USD",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "yaxes": [
    { "format": "currencyUSD", "label": "Per Group" }
   ],
   "targets": [
    {
     "expr": "sum(sett{param=\"usdBalance\"})",
     "legendFormat": "Grand Total"
    },
    {
     "expr": "sum(sett{token=~\".*crv.*\", param=\"usdBalance\"} )",
     "legendFormat": "Curve Pools"
    },
    {
     "expr": "sett{token=\"WBTC\", param=\"usdBalance\", chain=\"ETH\"} ",
     "legendFormat": "YEARN"
    },
    {
     "expr": "sett{token=\"slpWbtcEth\", param=\"usdBalance\"} ",
     "legendFormat": "WBTC/ETH LP"
    },
    {
     "expr": "sum(sett{token=~\".*(?i:(cvx).*)\", param=\"usdBalance\", chain=\"ETH\"} )",
     "legendFormat": "Convex Helpers"
    },
    {
     "expr": "sum(sett{token=~\".*WbtcBadger.*\", param=\"usdBalance\"})",
     "legendFormat": "BADGER LP"
    },
    {
     "expr": "sum(sett{token=~\".*WbtcDigg.*\", param=\"usdBalance\"})",
     "legendFormat": "DIGG LP"
    },
    {
     "expr": "sett{token=\"BADGER\", param=\"usdBalance\", chain=\"ETH\"} ",
     "legendFormat": "bBADGER"
    }
   ]
  },
  {
   "title": "Badger Treasury / Native Tokens Locked",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(wallets{token=\"BADGER\", param=\"balance\"}) ",
     "legendFormat": "{{token}}"
    },
    {
     "expr": "sum by (token) (wallets{token=~\"DIGG\", param=\"balance\"}) > 1  ",
     "legendFormat": "{{token}}"
    },
    {
     "expr": "sum(wallets{token=\"bBADGER\", param=\"balance\"}) > 10000"
    }
   ]
  },
  {
   "title": "AUM Per Chain",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (chain) (sett{param=\"usdBalance\", chain=~\"..*\"})",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Badger Treasury Holdings - Mutlichain - USD",
   "type": "graph",
   "description": "Note that native tokens are not included (bbadger, bdigg, digg, badger)\nAll badger wallets are watched",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "yaxes": [
    { "format": "currencyUSD", "label": "Ethereum" }
   ],
   "targets": [
    {
     "expr": "sum(wallets{param=\"usdBalance\", token!~\".*DIGG\", token!~\".*BADGER\",walletName!~\"uniswap_rewards\"}) ",
     "legendFormat": "Grand Total"
    },
    {
     "expr": "sum by(token) (wallets{param=\"usdBalance\", token!~\".*DIGG\", token!~\".*BADGER\",walletName!~\"uniswap_rewards\", chain=\"ETH\"}) != 0",
     "legendFormat": "ETH:{{token}}"
    },
    {
     "expr": "sum by(token) (wallets{param=\"usdBalance\", token!~\".*DIGG\", token!~\".*BADGER\",walletName!~\"uniswap_rewards\", chain=\"ARB\"}) != 0",
     "legendFormat": "ARB:{{token}}"
    }
   ]
  },
  {
   "title": "Native tokens per bToken",
   "type": "stat",
   "gridPos": { "h": 13, "w": 19, "x": 0, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sett{param=\"pricePerShare\", sett!~\"bDIGG\", chain=~\"..*\"}",
     "legendFormat": "{{chain}}:{{sett}}"
    },
    {
     "expr": "sett{param=\"balance\", sett=\"bDIGG\"} / on (sett) sett{param=\"totalSupply\", sett=\"bDIGG\"} *(10^9)",
     "legendFormat": "bDIGG"
    }
   ]
  }
 ]
}