{
 "title": "Sett Deposits Overview",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Badger Sett deposits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "bbadger" }
   ],
   "targets": [
    {
     "expr": "sett{param=\"totalSupply\", sett=~\".*bbadger.*\"}"
    },
    { "expression": "$A*$B", "type": "math" }
   ]
  },
  {
   "title": "Badger LP deposits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "BADGER" }
   ],
   "targets": [
    {
     "expression": "($uniBalance/$uniSupply)*$uniWBTC",
     "type": "math"
    },
    {
     "expression": "($uniBalance/$uniSupply)*$UniBADGER",
     "type": "math"
    },
    {
     "expression": "($sushiBalance/$sushiSupply)*$sushiWBTC",
     "type": "math"
    },
    {
     "expression": "($sushiBalance/$sushiSupply)*$sushiBADGER",
     "type": "math"
    },
    { "expression": "$SushiWBTC + $UniWBTC", "type": "math" },
    { "expression": "$SushiBADGER+ $UniBADGER", "type": "math" }
   ]
  },
  {
   "title": "Badger LP deposits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "BADGER" }
   ],
   "targets": [
    {
     "expression": "($uniBalance/$uniSupply)*$uniWBTC",
     "type": "math"
    },
    {
     "expression": "($uniBalance/$uniSupply)*$UniBADGER",
     "type": "math"
    },
    {
     "expression": "($sushiBalance/$sushiSupply)*$sushiWBTC",
     "type": "math"
    },
    {
     "expression": "($sushiBalance/$sushiSupply)*$sushiBADGER",
     "type": "math"
    },
    { "expression": "$SushiWBTC + $UniWBTC", "type": "math" },
    { "expression": "$SushiBADGER+ $UniBADGER", "type": "math" }
   ]
  },
  {
   "title": "DIGG Sett deposits",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "bdigg" }
   ],
   "targets": [
    {
     "expr": "sett{param=\"totalSupply\", sett=~\".*bdigg.*\"}"
    },
    { "expression": "(($A/$B)*1000000000)*$B", "type": "math" }
   ]
  },
  {
   "title": "Digg LP deposits",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "DIGG" }
   ],
   "targets": [
    {
     "expression": "($uniBalance/$uniSupply)*$uniWBTC",
     "type": "math"
    },
    {
     "expression": "($uniBalance/$uniSupply)*$UniDIGG",
     "type": "math"
    },
    {
     "expression": "($sushiBalance/$sushiSupply)*$sushiWBTC",
     "type": "math"
    },
    {
     "expression": "($sushiBalance/$sushiSupply)*$sushiDIGG",
     "type": "math"
    },
    { "expression": "$SushiWBTC + $UniWBTC", "type": "math" },
    { "expression": "$SushiDIGG+ $UniDIGG", "type": "math" }
   ]
  },
  {
   "title": "Sett Deposits - BTCesque denominated",
   "type": "graph",
   "description": "crv tokens that repreent a reasonably close 1/1 value with btc (although not exact)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "yaxes": [
    { "format": "currencyBTC", "label": "crv tokens" }
   ],
   "targets": [
    {
     "expr": "sett{param=\"balance\", sett=~\".*Crv.*\"}",
     "legendFormat": "{{sett}}"
    },
    {
     "expr": "sum(sett{param=\"balance\", sett=~\".*Crv.*\"})"
    }
   ]
  },
  {
   "title": "WBTC/ETH Sushi LP deposits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "ETH" }
   ],
   "targets": [
    {
     "expression": "($sushiBalance/$sushiSupply)*$sushiWBTC",
     "type": "math"
    },
    {
     "expression": "($sushiBalance/$sushiSupply)*$sushiETH",
     "type": "math"
    }
   ]
  }
 ]
}