{
 "title": "Native Btoken supply changes",
 "description": "NOTE that heatmaps only work right with timeframe set to \"last hour\"",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "bbadger supply (sett deposits)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bbadger" } },
   "yaxes": [
    { "format": "bbadger" }
   ],
   "targets": [
    {
     "expr": "sett{param=\"totalSupply\", sett=\"bbadger\"}"
    },
    { "expression": "${A}*${B}", "type": "math" }
   ]
  },
  {
   "title": "bDIGG supply (sets deposits)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bdigg" } },
   "yaxes": [
    { "format": "bdigg", "label": "Supply" }
   ],
   "targets": [
    {
     "expr": "{param=\"totalSupply\", sett=\"bdigg\"}"
    }
   ]
  },
  {
   "title": "bBADGER Supply Change Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "idelta(sett{param=\"totalSupply\", sett=\"bbadger\",instance=\"scout-collector:8801\",job=\"badger\"}[30s])"
    }
   ]
  },
  {
   "title": "bDIGG Supply Change Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "idelta(sett{param=\"totalSupply\", sett=\"bdigg\",instance=\"scout-collector:8801\",job=\"badger\"}[30s])"
    }
   ]
  }
 ]
}