{
 "title": "Badger Bitcoin Bridge Flow",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Bridge - Flow - Summary",
   "type": "stat",
   "description": "Bridge inflows and outflows, per token.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "token_flow_total{event=\"mint\", direction=\"in\", token=\"BTC\"}",
     "legendFormat": "BTC In (Minted)"
    },
    {
     "expr": "token_flow_total{event=\"burn\", direction=\"in\", token=\"WBTC\"}",
     "legendFormat": "WBTC In (Burned)"
    },
    {
     "expr": "token_flow_total{event=\"burn\", direction=\"in\", token=\"renBTC\"}",
     "legendFormat": "renBTC In (Burned)"
    },
    {
     "expr": "token_flow_total{event=\"burn\", direction=\"out\", token=\"BTC\"}",
     "legendFormat": "BTC Out (Burned)"
    },
    {
     "expr": "token_flow_total{event=\"mint\", direction=\"out\", token=\"WBTC\"}",
     "legendFormat": "WBTC Out (Minted)"
    },
    {
     "expr": "token_flow_total{event=\"mint\", direction=\"out\", token=\"renBTC\"}",
     "legendFormat": "renBTC Out (Minted)"
    }
   ]
  },
  {
   "title": "Bridge - Flow - Inflows vs. Outflows",
   "type": "graph",
   "description": "Bridge inflows and outflows, per token.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "token_flow_total{event=\"mint\", direction=\"in\", token=\"BTC\"}",
     "legendFormat": "BTC In (Minted)"
    },
    {
     "expr": "-token_flow_total{event=\"burn\", direction=\"out\", token=\"BTC\"}",
     "legendFormat": "BTC Out (Burned)"
    },
    {
     "expr": "token_flow_total{event=\"burn\", direction=\"in\", token=\"WBTC\"}",
     "legendFormat": "WBTC In (Burned)"
    },
    {
     "expr": "-token_flow_total{event=\"mint\", direction=\"out\", token=\"WBTC\"}",
     "legendFormat": "WBTC Out (Minted)"
    },
    {
     "expr": "token_flow_total{event=\"burn\", direction=\"in\", token=\"renBTC\"}",
     "legendFormat": "renBTC In (Burned)"
    },
    {
     "expr": "-token_flow_total{event=\"mint\", direction=\"out\", token=\"renBTC\"}",
     "legendFormat": "renBTC Out (Minted)"
    }
   ]
  },
  {
   "title": "Bridge - Flow - Totals",
   "type": "graph",
   "description": "Bridge (Inflows - Outflows), per token.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(token_flow_total{event=\"mint\", direction=\"in\", token=\"BTC\"}) - sum(token_flow_total{event=\"burn\", direction=\"out\", token=\"BTC\"})",
     "legendFormat": "BTC"
    },
    {
     "expr": "sum(token_flow_total{event=\"burn\", direction=\"in\", token=\"WBTC\"}) - sum(token_flow_total{event=\"mint\", direction=\"out\", token=\"WBTC\"})",
     "legendFormat": "WBTC"
    },
    {
     "expr": "sum(token_flow_total{event=\"mint\", direction=\"out\", token=\"renBTC\"}) - sum(token_flow_total{event=\"burn\", direction=\"in\", token=\"renBTC\"})",
     "legendFormat": "renBTC"
    }
   ]
  },
  {
   "title": "Bridge - Fees - Summary",
   "type": "stat",
   "description": "Fees collected by Badger DAO and Bridge team, RenVM Darknodes for Bridge transactions.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fees_total{entity=\"Badger DAO\"}",
     "legendFormat": "Badger DAO"
    },
    {
     "expr": "fees_total{entity=\"Badger Bridge Team\"}",
     "legendFormat": "Badger Bridge Team"
    },
    {
     "expr": "fees_total{entity=\"RenVM Darknodes\"}",
     "legendFormat": "RenVM Darknodes"
    }
   ]
  },
  {
   "title": "Bridge - Fees",
   "type": "graph",
   "description": "Fees collected by Badger DAO and Bridge team, RenVM Darknodes for Bridge transactions.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fees_total{entity=\"Badger DAO\"}",
     "legendFormat": "BadgerDAO"
    },
    {
     "expr": "fees_total{entity=\"Badger Bridge Team\"}",
     "legendFormat": "Badger Bridge Team"
    },
    {
     "expr": "fees_total{entity=\"RenVM Darknodes\"}",
     "legendFormat": "RenVM Darknodes"
    }
   ]
  },
  {
   "title": "Bridge - Flow - Breakdown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bridge - Flow Events - Summary",
     "type": "stat",
     "description": "Tokens minted and burned by Bridge transactions.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "token_flow_total{event=\"mint\", token=\"BTC\"}",
       "legendFormat": "BTC Minted"
      },
      {
       "expr": "token_flow_total{event=\"mint\", token=\"WBTC\"}",
       "legendFormat": "WBTC Minted"
      },
      {
       "expr": "token_flow_total{event=\"mint\", token=\"renBTC\"}",
       "legendFormat": "renBTC Minted"
      },
      {
       "expr": "token_flow_total{event=\"burn\", token=\"BTC\"}",
       "legendFormat": "BTC Burned"
      },
      {
       "expr": "token_flow_total{event=\"burn\", token=\"WBTC\"}",
       "legendFormat": "WBTC Burned"
      },
      {
       "expr": "token_flow_total{event=\"burn\", token=\"renBTC\"}",
       "legendFormat": "renBTC Burned"
      }
     ]
    },
    {
     "title": "Bridge - Flow Events - Mint",
     "type": "graph",
     "description": "Tokens minted by Bridge transactions.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "token_flow_total{event=\"mint\", token=\"BTC\"}",
       "legendFormat": "BTC"
      },
      {
       "expr": "token_flow_total{event=\"mint\", token=\"WBTC\"}",
       "legendFormat": "WBTC"
      },
      {
       "expr": "token_flow_total{event=\"mint\", token=\"renBTC\"}",
       "legendFormat": "renBTC"
      }
     ]
    },
    {
     "title": "Bridge - Flow Events - Burn",
     "type": "graph",
     "description": "Tokens burned by Bridge transactions.",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "token_flow_total{event=\"burn\", token=\"BTC\"}",
       "legendFormat": "BTC"
      },
      {
       "expr": "token_flow_total{event=\"burn\", token=\"WBTC\"}",
       "legendFormat": "WBTC"
      },
      {
       "expr": "token_flow_total{event=\"burn\", token=\"renBTC\"}",
       "legendFormat": "renBTC"
      }
     ]
    },
    {
     "title": "Bridge - Flow Direction - Summary",
     "type": "stat",
     "description": "Tokens received in and sent out by Bridge transactions.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 30 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "token_flow_total{direction=\"in\", token=\"BTC\"}",
       "legendFormat": "BTC In"
      },
      {
       "expr": "token_flow_total{direction=\"in\", token=\"WBTC\"}",
       "legendFormat": "WBTC In"
      },
      {
       "expr": "token_flow_total{direction=\"in\", token=\"renBTC\"}",
       "legendFormat": "renBTC In"
      },
      {
       "expr": "token_flow_total{direction=\"out\", token=\"BTC\"}",
       "legendFormat": "BTC Out"
      },
      {
       "expr": "token_flow_total{direction=\"out\", token=\"WBTC\"}",
       "legendFormat": "WBTC Out"
      },
      {
       "expr": "token_flow_total{direction=\"in\", token=\"renBTC\"}",
       "legendFormat": "renBTC Out"
      }
     ]
    },
    {
     "title": "Bridge - Flow Direction - In",
     "type": "graph",
     "description": "Tokens received in by Bridge transactions.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "token_flow_total{direction=\"in\", token=\"BTC\"}",
       "legendFormat": "BTC"
      },
      {
       "expr": "token_flow_total{direction=\"in\", token=\"WBTC\"}",
       "legendFormat": "WBTC"
      },
      {
       "expr": "token_flow_total{direction=\"in\", token=\"renBTC\"}",
       "legendFormat": "renBTC"
      }
     ]
    },
    {
     "title": "Bridge - Flow Direction - Out",
     "type": "graph",
     "description": "Tokens sent out by Bridge transactions.",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "token_flow_total{direction=\"out\", token=\"BTC\"}",
       "legendFormat": "BTC"
      },
      {
       "expr": "token_flow_total{direction=\"out\", token=\"WBTC\"}",
       "legendFormat": "WBTC"
      },
      {
       "expr": "token_flow_total{direction=\"out\", token=\"renBTC\"}",
       "legendFormat": "renBTC"
      }
     ]
    }
   ]
  }
 ]
}