{
 "title": "Treasury",
 "description": "A overview across all of our wallets and what the DAO holds",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Totals - USD Normalized",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "yaxes": [
    { "format": "currencyUSD", "label": "Tokens" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by(token) (wallets{param=\"usdBalance\", token!~\".*DIGG\", token!~\".*BADGER\", walletName!~\"uniswap_rewards\"}) != 0)",
     "legendFormat": "{{token}}"
    },
    {
     "expr": "sum(wallets{param=\"usdBalance\", token!~\".*DIGG\", token!~\".*BADGER\", walletName!~\"uniswap_rewards\"})",
     "legendFormat": "Grand Total"
    }
   ]
  },
  {
   "title": "Curve Pools",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "crv token" }
   ],
   "targets": [
    {
     "expr": "sum by(token) (wallets{token=~\"crv.*\", param=\"balance\"} *  on(token) group_left crvtokens{token=~\"crv.*\", param=\"pricePerShare\"})",
     "legendFormat": "{{token}} - btc"
    },
    {
     "expr": "sum by(token) (wallets{token=~\"crv.*\", param=\"balance\"})",
     "legendFormat": "{{token}} - crv"
    },
    {
     "expr": "sum (wallets{token=~\"crv.*\", param=\"balance\"})",
     "legendFormat": "Total - crv"
    },
    {
     "expr": "sum(wallets{token=~\"crv.*\", param=\"balance\"} *  on(token) group_left crvtokens{token=~\"crv.*\", param=\"pricePerShare\"})",
     "legendFormat": "Total - btc"
    }
   ]
  },
  {
   "title": "Curve Pools",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (token) (wallets{token=~\".*crv.*\", param=\"usdBalance\"} != 0)",
     "legendFormat": "{{token}} - USD value"
    },
    {
     "expr": "sum(wallets{token=~\".*crv.*\", param=\"usdBalance\"} != 0)",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "WBTC/ETH LP tokens (Underlying)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "currencyBTC" }
   ],
   "targets": [
    {
     "expr": "(sum(wallets{token=\"slpWbtcEth\",param=\"balance\"}) / sum(lptokens{token=\"slpWbtcEth\",param=\"totalLpTokenSupply\"})) * sum(lptokens{token=\"slpWbtcEth\", param=\"WETH_supply\"})"
    },
    {
     "expr": "(sum(wallets{token=\"slpWbtcEth\", param=\"balance\"}) / sum(lptokens{token=\"slpWbtcEth\",param=\"totalLpTokenSupply\"})) * sum(lptokens{token=\"slpWbtcEth\", param=\"WBTC_supply\"})"
    }
   ]
  },
  {
   "title": "WBTC/ETH LP  (USD) + LP Token Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "USD Value" }
   ],
   "targets": [
    {
     "expr": "sum(wallets{token=\"slpWbtcEth\", param=\"usdBalance\"})",
     "legendFormat": "USD"
    },
    {
     "expr": "sum(wallets{token=\"slpWbtcEth\", param=\"balance\"})",
     "legendFormat": "LP Tokens"
    }
   ]
  },
  {
   "title": "Supersett Tokens",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "FARM" }
   ],
   "targets": [
    {
     "expr": "(wallets{token=~\"xSUSHI\", param=\"balance\"}) != 0   ",
     "legendFormat": "{{token}} - {{walletName}}"
    },
    {
     "expr": "(wallets{token=~\"FARM\", param=\"balance\"}) != 0",
     "legendFormat": "{{token}} - {{walletName}}"
    }
   ]
  },
  {
   "title": "Supersett Tokens - Fees (USD)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "yaxes": [
    { "format": "currencyUSD", "label": "USD (1 million +)" }
   ],
   "targets": [
    {
     "expr": "sum by (token) (wallets{token=~\"xSUSHI\", param=\"usdBalance\", walletName!~\"badgertree\"})",
     "legendFormat": "{{token}} - USD"
    },
    {
     "expr": "sum by (token) (wallets{token=~\"FARM\", param=\"usdBalance\", walletName!~\"badgertree\"})",
     "legendFormat": "{{token}} - USD"
    },
    { "expression": "$A+$B", "type": "math" }
   ]
  },
  {
   "title": "Badgretree - Rewards to be claimed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "wallets{walletName=\"badgertree\", param=\"usdBalance\"} != 0  ",
     "legendFormat": "{{token}}"
    }
   ]
  }
 ]
}