{
 "title": "ibBTC",
 "time": { "from": "2021-05-27T03:42:38.563Z", "to": "2021-05-27T03:49:21.752Z" },
 "panels": [
  {
   "title": "ibBTC Supply",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ibBTC{param=\"totalSupply\"}",
     "legendFormat": "ibBTC Total Supply"
    },
    {
     "expr": "ibbtc_token_flow_total{token=\"ibBTC\", event=\"mint\", direction=\"out\"}",
     "legendFormat": "ibBTC Minted"
    },
    {
     "expr": "ibbtc_token_flow_total{token=\"ibBTC\", event=\"burn\", direction=\"in\"}",
     "legendFormat": "ibBTC Redeemed"
    }
   ]
  },
  {
   "title": "ibBTC - Fees ",
   "type": "stat",
   "description": "Fees collected by Badger DAO and DefiDollar from ibBTC Mint and Redeem transactions.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ibbtc_fees_total{})", "legendFormat": "Total" },
    {
     "expr": "ibbtc_fees_total{entity=\"Badger DAO\"}",
     "legendFormat": "Badger DAO"
    },
    {
     "expr": "ibbtc_fees_total{entity=\"DefiDollar\"}",
     "legendFormat": "DefiDollar"
    }
   ]
  },
  {
   "title": "ibBTC Supply",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ibBTC{param=\"totalSupply\"}",
     "legendFormat": "ibBTC Total Supply"
    }
   ]
  },
  {
   "title": "Peak Composition",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ibBTC_composition{param=\"balance\", tokenName=\"bcrvRenBTC\"}",
     "legendFormat": "bcrvRenBTC"
    },
    {
     "expr": "ibBTC_composition{param=\"balance\", tokenName=\"bcrvSBTC\"}",
     "legendFormat": "bcrvSBTC"
    },
    {
     "expr": "ibBTC_composition{param=\"balance\", tokenName=\"bcrvTBTC\"}",
     "legendFormat": "bcrvTBTC"
    },
    {
     "expr": "ibBTC_composition{param=\"balance\", tokenName=\"byvWBTC\"}",
     "legendFormat": "byvWBTC"
    }
   ]
  }
 ]
}