{
 "title": "Rewards availability",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Time since last cycle",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "time()-(badgertree)" }
   ]
  },
  {
   "title": "Badger in Badgertree",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rewards{token=\"BADGER\"}",
     "legendFormat": "{{token}}"
    }
   ]
  },
  {
   "title": "Digg in Badgertree",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rewards{token='DIGG'}", "legendFormat": "{{token}}" }
   ]
  }
 ]
}