{
 "title": "Sett Deposits/AUM Overview",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Total AUM - USD",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "yaxes": [
    { "format": "currencyUSD", "label": "Per Group" }
   ],
   "targets": [
    {
     "expr": "sum(sett{token=~\".*crv.*\", param=\"balance\"}  * on (token) sett{token=~\".*crv.*\", param=\"pricePerShare\"}) * sum(coingecko_prices{token=\"WBTC\", countercurrency=\"usd\"})",
     "legendFormat": "Curve Setts"
    },
    {
     "expr": "sum(sett{token=~\"WBTC\", param=\"balance\"}  * on (token) sett{token=~\"WBTC\", param=\"pricePerShare\"}) * sum(coingecko_prices{token=\"WBTC\", countercurrency=\"usd\"})",
     "legendFormat": "Yearn WBTC Sett"
    },
    {
     "expr": "sett{token=\"slpWbtcEth\", param=\"balance\"}  * on(token) lptokens{token=\"slpWbtcEth\", param=\"usdPricePerShare\"}",
     "legendFormat": "WBTC/ETH LP"
    },
    {
     "expr": "sum(sett{token=~\".*WbtcBadger.*\", param=\"balance\"} * on(token) lptokens{token=~\".*WbtcBadger.*\", param=\"usdPricePerShare\"})",
     "legendFormat": "BADGER LP"
    },
    {
     "expr": "sum(sett{token=~\".*WbtcDigg.*\", param=\"balance\"} * on(token) lptokens{token=~\".*WbtcDigg.*\", param=\"usdPricePerShare\"})",
     "legendFormat": "DIGG LP"
    },
    {
     "expr": "sett{token=\"DIGG\", param=\"totalSupply\"} * on (token) sett{token=\"DIGG\", param=\"pricePerShare\"} * on(token) coingecko_prices{token=\"DIGG\", countercurrency=\"usd\"}",
     "legendFormat": "bDIGG"
    },
    {
     "expr": "sett{token=\"BADGER\", param=\"totalSupply\"} * on (token) sett{token=\"BADGER\", param=\"pricePerShare\"} * on(token) coingecko_prices{token=\"BADGER\", countercurrency=\"usd\"}",
     "legendFormat": "bBADGER"
    },
    { "expression": "$A+$B+$C+$D+$E+$F+$H", "type": "math" }
   ]
  },
  {
   "title": "Sett Deposits - BTCesque denominated",
   "type": "graph",
   "description": "crv tokens that repreent a reasonably close 1/1 value with btc (although not exact)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "yaxes": [
    { "format": "currencyBTC", "label": "pools" }
   ],
   "targets": [
    {
     "expr": "sett{param=\"balance\", sett=~\"byvWBTC\"}",
     "legendFormat": "{{sett}}"
    },
    {
     "expr": "sett{param=\"balance\", sett=~\".*crv.*\"}",
     "legendFormat": "{{sett}}"
    },
    {
     "expr": "sum(sett{param=\"balance\", sett=~\".*crv.*\"}) + sum(sett{param=\"balance\", sett=~\"byvWBTC\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Badger LP deposits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(sett{token=~\".*WbtcBadger\", param=\"balance\"} /  on (token) (lptokens{token=~\".*WbtcBadger\",param=\"totalLpTokenSupply\"})) *  on (token) (lptokens{token=~\".*WbtcBadger\", param=\"BADGER_supply\"})",
     "legendFormat": "{{token}} -  BADGER"
    },
    {
     "expr": "(sett{token=~\".*WbtcBadger\", param=\"balance\"} /  on (token) (lptokens{token=~\".*WbtcBadger\",param=\"totalLpTokenSupply\"})) *  on (token) (lptokens{token=~\".*WbtcBadger\", param=\"WBTC_supply\"})",
     "legendFormat": "{{token}} - WBTC"
    }
   ]
  },
  {
   "title": "Badger Sett deposits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "BADGER" }
   ],
   "targets": [
    {
     "expr": "sett{param=\"totalSupply\", sett=\"bBADGER\"}",
     "legendFormat": "bBADGER"
    },
    {
     "expr": "sett{param=\"pricePerShare\", sett=\"bBADGER\"} * on (sett) sett{param=\"totalSupply\", sett=\"bBADGER\"}",
     "legendFormat": "BADGER"
    }
   ]
  },
  {
   "title": "Digg LP deposits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "DIGG" }
   ],
   "targets": [
    {
     "expr": "(sett{token=~\".*WbtcDigg\", param=\"balance\"} /  on (token) (lptokens{token=~\".*WbtcDigg\",param=\"totalLpTokenSupply\"})) *  on (token) (lptokens{token=~\".*WbtcDigg\", param=\"DIGG_supply\"})  ",
     "legendFormat": "{{token}} - DIGG"
    },
    {
     "expr": "(sett{token=~\".*WbtcDigg\", param=\"balance\"} /  on (token) (lptokens{token=~\".*WbtcDigg\",param=\"totalLpTokenSupply\"})) *  on (token) (lptokens{token=~\".*WbtcDigg\", param=\"WBTC_supply\"})  ",
     "legendFormat": "{{token}} - WBTC"
    }
   ]
  },
  {
   "title": "DIGG Sett deposits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "DIGG" }
   ],
   "targets": [
    {
     "expr": "sett{param=\"totalSupply\", sett=~\"bDIGG\"}",
     "legendFormat": "{{sett}}"
    },
    {
     "expr": "sett{param=\"totalSupply\", sett=~\"bDIGG\"} * on (sett)  sett{param=\"pricePerShare\", sett=\"bDIGG\"}",
     "legendFormat": "DIGG"
    }
   ]
  },
  {
   "title": "slpWbtcEth LP Tokens",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sett{token=\"slpWbtcEth\",param=\"balance\"} ",
     "legendFormat": "WBTC/ETH slp tokens"
    }
   ]
  },
  {
   "title": "WBTC/ETH Sushi LP deposits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "ETH" }
   ],
   "targets": [
    {
     "expr": "(sett{token=\"slpWbtcEth\",param=\"balance\"}  / on(token)   lptokens{token=\"slpWbtcEth\",param=\"totalLpTokenSupply\"}) * on(token) lptokens{token=\"slpWbtcEth\", param=~\"WETH_supply\"}",
     "legendFormat": "ETH"
    },
    {
     "expr": "(sett{token=\"slpWbtcEth\",param=\"balance\"}  / on(token)   lptokens{token=\"slpWbtcEth\",param=\"totalLpTokenSupply\"}) * on(token) lptokens{token=\"slpWbtcEth\", param=~\"WBTC_supply\"}",
     "legendFormat": "WBTC"
    }
   ]
  }
 ]
}